if(DEFINED ENV{DEPOT_TOOLS})
  set(DEPOT_TOOLS "$ENV{DEPOT_TOOLS}")
elseif(WIN32)
  set(DEPOT_TOOLS "$ENV{USERPROFILE}/depot_tools")
else()
  set(DEPOT_TOOLS "$ENV{HOME}/depot_tools")
endif()

if(WIN32)
  set(ENV{PATH} "${DEPOT_TOOLS};$ENV{PATH}")
else()
  set(ENV{PATH} "${DEPOT_TOOLS}:$ENV{PATH}")
endif()

get_filename_component(LLVM_BIN "${CMAKE_CXX_COMPILER}" DIRECTORY)
get_filename_component(LLVM_ROOT "${LLVM_BIN}" DIRECTORY)

set(GN_COMMAND "bin/gn" gen "${skia_BINARY_DIR}")
file(WRITE "${skia_BINARY_DIR}/args.gn" "")
if("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
  file(APPEND "${skia_BINARY_DIR}/args.gn" "is_official_build=true\n")
else()
  file(APPEND "${skia_BINARY_DIR}/args.gn" "extra_cflags=[\"/MTd\", \"/D_DEBUG\", \"/D_ITERATOR_DEBUG_LEVEL=2\"]\n")
endif()
if(WIN32)
  file(APPEND "${skia_BINARY_DIR}/args.gn" "extra_ldflags=[\"Ws2_32.lib\"]\n")
endif()
file(APPEND "${skia_BINARY_DIR}/args.gn" "clang_win=\"${LLVM_ROOT}\"\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_expat=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_harfbuzz=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_icu=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_libjpeg_turbo=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_libpng=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_libwebp=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_zlib=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_perfetto=true\n")

execute_process(COMMAND ${GN_COMMAND})
execute_process(COMMAND cmake -E touch_nocreate "${skia_BINARY_DIR}/build.ninja")
