if(DEFINED ENV{DEPOT_TOOLS})
  set(DEPOT_TOOLS "$ENV{DEPOT_TOOLS}")
elseif(WIN32)
  set(DEPOT_TOOLS "$ENV{USERPROFILE}/depot_tools")
else()
  set(DEPOT_TOOLS "$ENV{HOME}/depot_tools")
endif()

if(WIN32)
  set(ENV{PATH} "${DEPOT_TOOLS};$ENV{PATH}")
else()
  set(ENV{PATH} "${DEPOT_TOOLS}:$ENV{PATH}")
endif()

set(extra_cflags "[]")
foreach(flag ${CMAKE_CXX_FLAGS})
  string(JSON extra_cflags SET "${extra_cflags}" 1000 "\"${flag}\"")
endforeach()

set(extra_ldflags "[]")
foreach(flag ${CMAKE_EXE_LINKER_FLAGS})
  string(JSON extra_ldflags SET "${extra_ldflags}" 1000 "\"${flag}\"")
endforeach()

if(WIN32)
  string(JSON extra_cflags SET "${extra_cflags}" 1000 "\"/MTd\"")
  string(JSON extra_cflags SET "${extra_cflags}" 1000 "\"/D_DEBUG\"")
  string(JSON extra_cflags SET "${extra_cflags}" 1000 "\"/D_ITERATOR_DEBUG_LEVEL=2\"")
  string(JSON extra_ldflags SET "${extra_ldflags}" 1000 "\"Ws2_32.lib\"")
else()
endif()

set(GN_COMMAND "bin/gn" gen "${skia_BINARY_DIR}")
file(WRITE "${skia_BINARY_DIR}/args.gn" "")
if("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
  file(APPEND "${skia_BINARY_DIR}/args.gn" "is_official_build=true\n")
endif()
if(WIN32)
  get_filename_component(LLVM_BIN "${CMAKE_CXX_COMPILER}" DIRECTORY)
  get_filename_component(LLVM_ROOT "${LLVM_BIN}" DIRECTORY)
  file(APPEND "${skia_BINARY_DIR}/args.gn" "clang_win=\"${LLVM_ROOT}\"\n")
else()
  file(APPEND "${skia_BINARY_DIR}/args.gn" "cc=\"clang\"\n")
  file(APPEND "${skia_BINARY_DIR}/args.gn" "cxx=\"clang++\"\n")
endif()
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_expat=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_harfbuzz=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_icu=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_libjpeg_turbo=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_libpng=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_libwebp=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_zlib=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_system_freetype2=false\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "skia_use_perfetto=true\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "extra_cflags=${extra_cflags}\n")
file(APPEND "${skia_BINARY_DIR}/args.gn" "extra_ldflags=${extra_ldflags}\n")

execute_process(COMMAND ${GN_COMMAND})
execute_process(COMMAND cmake -E touch_nocreate "${skia_BINARY_DIR}/build.ninja")
